# Generated by Django 3.2.14 on 2022-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_variation_variation_category'),
        ('carts', '0002_auto_20220902_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='shop.Variation'),
        ),
    ]
