# Generated by Django 3.2.14 on 2022-09-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-category_name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
