# Generated by Django 3.2.14 on 2022-08-23 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_name', models.CharField(max_length=100, unique=True)),
                ('tea_type', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('origin', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('aroma', models.CharField(blank=True, max_length=100)),
                ('taste', models.CharField(blank=True, max_length=100)),
                ('tea_nature', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=False)),
                ('properties', models.TextField(blank=True, max_length=300)),
                ('weight', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/products/%Y/%m/%d')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('stars', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
